name: Download Models

# Ausgelöst bei Push oder Pull Request
on:
  push:
  pull_request:

jobs:
  fetch-models:
    name: Fetch and Verify Models
    runs-on: ubuntu-latest
    steps:

      # 1) Hol dir den Code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Python-Umgebung einrichten
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3) Abhängigkeiten installieren (requests)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # 4) Modelle herunterladen
      - name: Run download_models.py
        run: |
          python download_models.py

      # 5) Verifizieren, dass alle Dateien existieren
      - name: Verify downloaded weights
        run: |
          ls -la models/weights
          for file in table5_pidinet.pth diffedge_swin.pth edter_bsds.pth; do
            if [ ! -f models/weights/$file ]; then
              echo "ERROR: $file fehlt!"
              exit 1
            fi
          done
          echo "Alle Gewichtungsdateien erfolgreich vorhanden."

      # 6) Artefakte hochladen mit v4 der Action
      - name: Upload weights as artifact
        uses: actions/upload-artifact@v4
        with:
          name: model-weights
          path: models/weights
