name: Download Models

on:
  push:
  pull_request:

jobs:
  fetch-models:
    name: Fetch and Verify Models
    runs-on: ubuntu-latest

    steps:
      # 1) Code auschecken
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Python 3.10 installieren
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3) Requests installieren
      - name: Install requests
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # 4) Modelle herunterladen
      - name: Run download_models.py
        run: |
          python download_models.py

      # 5) SHA-256 prüfen (muss zu download_models.py passen)
      - name: Verify SHA-256 hashes
        run: |
          declare -A SHAS
          SHAS[table5_pidinet.pth]="80860ac267258b5f27486e0ef152a211d0b08120f62aeb185a050acc30da486c"
          SHAS[diffedge_swin.pth]="83c6e6cfbb7d0bfa99b65f74116a3f2a019e81d479f40c710120cbb0e800c4fd"
          SHAS[edter_bsds.pth]="d15a3d1e0e9cc2e83332bb19a4d6fd2936053c39e27e91ce2ae7623d5551e6a7"
          cd models/weights
          for file in "${!SHAS[@]}"; do
            if [[ ! -f "$file" ]]; then
              echo "ERROR: $file fehlt!"
              exit 1
            fi
            HASH=$(sha256sum "$file" | awk '{print $1}')
            if [[ "$HASH" != "${SHAS[$file]}" ]]; then
              echo "ERROR: Hash-Mismatch bei $file"
              exit 1
            fi
            echo "$file OK"
          done
          echo "Alle Dateien vorhanden und Hash geprüft."

      # 6) Artefakte hochladen
      - name: Upload weight files
        uses: actions/upload-artifact@v4
        with:
          name: model-weights
          path: models/weights
